export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"Software Engineering Apprenticeship"},["/README.md"]],
  ["v-2e2bd854","/behaviours/b01.html",{"title":"B1: works independently and takes responsibility"},[":md"]],
  ["v-2ac22716","/behaviours/b02.html",{"title":"B2: applies logical thinking"},[":md"]],
  ["v-275875d8","/behaviours/b03.html",{"title":"B3: maintains a productive, professional and secure working environment"},[":md"]],
  ["v-23eec49a","/behaviours/b04.html",{"title":"B4: works collaboratively with a wide range of people in different roles, internally and externally, with a positive attitude to inclusion & diversity"},[":md"]],
  ["v-2085135c","/behaviours/b05.html",{"title":"B5: acts with integrity with respect to ethical, legal and regulatory ensuring the protection of personal data, safety and security"},[":md"]],
  ["v-1d1b621e","/behaviours/b06.html",{"title":"B6: shows initiative and takes responsibility for solving problems within their own remit, being resourceful when faced with a problem to solve"},[":md"]],
  ["v-19b1b0e0","/behaviours/b07.html",{"title":"B7: communicates effectively in a variety of situations to both a technical and non-technical audience"},[":md"]],
  ["v-1647ffa2","/behaviours/b08.html",{"title":"B8: shows curiosity to the business context in which the solution will be used, displaying an inquisitive approach to solving the problem"},[":md"]],
  ["v-12de4e64","/behaviours/b09.html",{"title":"B9: committed to continued professional development"},[":md"]],
  ["v-1e7bc794","/duties/d01.html",{"title":"D1: take and interpret given software development requirements to estimate effort to deliver the work product to enable accurate costs to be established."},[":md"]],
  ["v-1b121656","/duties/d02.html",{"title":"D2: break software development activities down into logical units of work to enable sequencing and ensure the best possible structuring of activities to deliver a high quality product right first time."},[":md"]],
  ["v-17a86518","/duties/d03.html",{"title":"D3: report progress accurately throughout the development life-cycle stages to ensure adequate audit trails of key worksteps such that the organisation can demonstrate how the product has been created for quality and commercial purposes."},[":md"]],
  ["v-143eb3da","/duties/d04.html",{"title":"D4: identify and report any impediments to software development activities and propose practical solutions."},[":md"]],
  ["v-10d5029c","/duties/d05.html",{"title":"D5: convert customer requirements into technical requirements, both functional and non-functional to ensure that customers' expectations are accurately reflected in the software products developed."},[":md"]],
  ["v-0d6b515e","/duties/d06.html",{"title":"D6: identify and select the most appropriate technical solution, taking into consideration coding best practice and appropriate quality standards."},[":md"]],
  ["v-0a01a020","/duties/d07.html",{"title":"D7: communicate software development solutions to a range of internal or external stakeholders to ensure clear understanding of requirements and how they have been met or adjusted."},[":md"]],
  ["v-0697eee2","/duties/d08.html",{"title":"D8: consider security implications of proposed design to ensure that security considerations are built in from inception and throughout the development process."},[":md"]],
  ["v-032e3da4","/duties/d09.html",{"title":"D9: write logical and maintainable software solutions to meet the design and organisational coding standards (Software Development Lifecycle - Implementation and Build phase)."},[":md"]],
  ["v-23f37ed8","/duties/d10.html",{"title":"D10: apply security best practice to the software solution throughout the software development life-cycle."},[":md"]],
  ["v-25a85777","/duties/d11.html",{"title":"D11: create and maintain appropriate project documentation to explain the development process and resources used."},[":md"]],
  ["v-275d3016","/duties/d12.html",{"title":"D12: apply appropriate recovery techniques to ensure the software solution being developed is not lost (Software Development Lifecycle - Implementation and Build phase)."},[":md"]],
  ["v-291208b5","/duties/d13.html",{"title":"D13: implement appropriate change control to ensure that software development changes may be tracked and quality risks managed."},[":md"]],
  ["v-2ac6e154","/duties/d14.html",{"title":"D14: undertake unit testing of solutions, with appropriate levels of test code coverage, to identify and, where necessary, resolve issues (Software Development Lifecycle -Implementation and Build phase)."},[":md"]],
  ["v-2c7bb9f3","/duties/d15.html",{"title":"D15: perform testing of the software solution to ensure a high quality output (Software Development Lifecycle -Test phase)."},[":md"]],
  ["v-2e309292","/duties/d16.html",{"title":"D16: deliver a suitably documented deployable solution to the customer for their use (Software Development Lifecycle -Deploy phase)."},[":md"]],
  ["v-2fe56b31","/duties/d17.html",{"title":"D17: support delivery of one or more software deployment phases, such as trials and final release, to ensure that software developer outcomes are deployed correctly."},[":md"]],
  ["v-319a43d0","/duties/d18.html",{"title":"D18: provide support during software trials and after final release to ensure that customers understand and can correctly apply the product, and risks are mitigated."},[":md"]],
  ["v-334f1c6f","/duties/d19.html",{"title":"D19: respond appropriately to given Service Level Agreements (SLAs) to ensure that time and resources invested in software development activity are allocated appropriately to deliver good customer service."},[":md"]],
  ["v-58d9ba19","/duties/d20.html",{"title":"D20: apply suitable 'bug fix', appropriate to the severity and priority of the software development issue identified."},[":md"]],
  ["v-5a8e92b8","/duties/d21.html",{"title":"D21: practice continuous self learning to keep up to date with technological developments to enhance relevant skills and take responsibility for own professional development."},[":md"]],
  ["v-d4567c52","/knowledge/k01.html",{"title":"K1: all stages of the software development life-cycle (what each stage contains, including the inputs and outputs)"},[":md"]],
  ["v-d0eccb14","/knowledge/k02.html",{"title":"K2: roles and responsibilities within the software development lifecycle (who is responsible for what)"},[":md"]],
  ["v-cd8319d6","/knowledge/k03.html",{"title":"K3: the roles and responsibilities of the project life-cycle within your organisation, and your role"},[":md"]],
  ["v-ca196898","/knowledge/k04.html",{"title":"K4: how best to communicate using the different communication methods and how to adapt appropriately to different audiences"},[":md"]],
  ["v-c6afb75a","/knowledge/k05.html",{"title":"K5: the similarities and differences between different software development methodologies, such as agile and waterfall"},[":md"]],
  ["v-c346061c","/knowledge/k06.html",{"title":"K6: how teams work effectively to produce software and how to contribute appropriately"},[":md"]],
  ["v-bfdc54de","/knowledge/k07.html",{"title":"K7: software design approaches and patterns, to identify reusable solutions to commonly occurring problems"},[":md"]],
  ["v-bc72a3a0","/knowledge/k08.html",{"title":"K8: organisational policies and procedures relating to the tasks being undertaken, and when to follow them. For example the storage and treatment of GDPR sensitive data"},[":md"]],
  ["v-b908f262","/knowledge/k09.html",{"title":"K9: algorithms, logic and data structures relevant to software development for example:- arrays- stacks- queues- linked lists- trees- graphs- hash tables- sorting algorithms- searching algorithms- critical sections and race conditions"},[":md"]],
  ["v-6df3b70e","/knowledge/k10.html",{"title":"K10: principles and uses of relational and non-relational databases"},[":md"]],
  ["v-6a8a05d0","/knowledge/k11.html",{"title":"K11: software designs and functional or technical specifications"},[":md"]],
  ["v-67205492","/knowledge/k12.html",{"title":"K12: software testing frameworks and methodologies"},[":md"]],
  ["v-61d9a2b9","/skills/s01.html",{"title":"S1: create logical and maintainable code"},[":md"]],
  ["v-638e7b58","/skills/s02.html",{"title":"S2: develop effective user interfaces"},[":md"]],
  ["v-654353f7","/skills/s03.html",{"title":"S3: link code to data sets"},[":md"]],
  ["v-66f82c96","/skills/s04.html",{"title":"S4: test code and anylsing results to correct errors found using unit testing"},[":md"]],
  ["v-68ad0535","/skills/s05.html",{"title":"S5: conduct a range of test types, such as Integration, System, User Acceptance, Non-Functional, Performance and Securitu testing"},[":md"]],
  ["v-6a61ddd4","/skills/s06.html",{"title":"S6: identify and create test scenarios"},[":md"]],
  ["v-6c16b673","/skills/s07.html",{"title":"S7: apply structured techniques to problem solving, debug code and understand the structure of programmes in order to identify and resolve issues"},[":md"]],
  ["v-6dcb8f12","/skills/s08.html",{"title":"S8: create simple software designs to effectively communicate understanding of the program"},[":md"]],
  ["v-6f8067b1","/skills/s09.html",{"title":"S9: create analysis artefacts, such as use cases and/or user stories"},[":md"]],
  ["v-d5e9f54a","/skills/s10.html",{"title":"S10: build, manage and deploy code into the relevant environment"},[":md"]],
  ["v-d280440c","/skills/s11.html",{"title":"S11: apply an appropriate software development approach according to the relevant paradigm (for example object oriented, event driven or procedural)"},[":md"]],
  ["v-cf1692ce","/skills/s12.html",{"title":"S12: follow software designs and functional or technical specifications"},[":md"]],
  ["v-cbace190","/skills/s13.html",{"title":"S13: follow testing frameworks and methodologies"},[":md"]],
  ["v-c8433052","/skills/s14.html",{"title":"S14: follow company, team or client approaches to continuous integration, version and source control"},[":md"]],
  ["v-c4d97f14","/skills/s15.html",{"title":"S15: communicate software solutions and ideas to technical and non-technical stakeholders"},[":md"]],
  ["v-c16fcdd6","/skills/s16.html",{"title":"S16: apply algorithms, logic and data structures"},[":md"]],
  ["v-be061c98","/skills/s17.html",{"title":"S17: interpret and implement a given design whist remaining compliant with security and maintainability requirements"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
